### ISSUE TITLE
sr-scan should ignore non VDI snaps

### ISSUE THREAD

**Issue by Emmenemoi** [rposudnevskiy/RBDSR#16]
I'm using non xenserver tools to backup RBD images to a disaster recovery site using snap+export.
Unfortunately sr-scan tries to import those not protected snaps (1 per image).

This should not fail but just ignore them (everything that is not XS origins, using snap prefix):

Error code: SR_BACKEND_FAILURE_40
Error parameters: , The SR scan failed  [opterr=['UUID_INVALID', 'VDI', 'backup2016-08-23T10.16.08']],

**Comment by Emmenemoi** [comment]
Needs some quick review for the future (regarding CLONE_PREFIX).

**Comment by rposudnevskiy** [comment]
Hi,
CLONE_PREFIX is the same as VDI_PREFIX.
In the beginning I thought to use different prefixes for the usual image and for the clone, but then I realized that there was no need for it, but I didn't have time to rewrite the code and I decided to keep it as is.
It is possible to replace all occurrences of CLONE_PREFIX by VDI_PREFIX
Sorry for too late answer.
