### ISSUE TITLE
Use of some files

### ISSUE THREAD

**Issue by maxcuttins** [rposudnevskiy/RBDSR#26]
In the repo there some files that are included but there is no explanation about how and where to install them.

What are these files:
* tap-ctl
* vhd-tool

used for?

Do I need to install theme?
Where?

**Comment by chenull** [comment]
I think the explanation is [here](https://github.com/rposudnevskiy/RBDSR/blob/master/HOWTOs/Add_support_for_xe_vdi-export.md). They are used for supporting `xe vdi-export`

**Comment by maxcuttins** [comment]
THANKS!!!!!
