### ISSUE TITLE
Why default device is rbd-nbd instead of rbd-kernel?

### ISSUE THREAD

**Issue by maxcuttins** [rposudnevskiy/RBDSR#28]
I'm not aware about the diff between these 2 devices.
Then why nbd default and not kernel?

Is it a choice based on performance?

**Comment by rposudnevskiy** [comment]
Hi,
The kernel mode is the fastest but XenServer dom0 has a pretty old kernel and doesn't support  all features of last Ceph releases. [http://docs.ceph.com/docs/master/start/os-recommendations/](http://docs.ceph.com/docs/master/start/os-recommendations/)
The rbd-nbd and rbd-fuse support all features but rbd-fuse is slower then rbd-nbd so it was decided to use rbd-nbd. [https://github.com/rposudnevskiy/RBDSR/issues/4](https://github.com/rposudnevskiy/RBDSR/issues/4)

**Comment by maxcuttins** [comment]
Very good news.
Then i don't need to issue:

`ceph osd crush tunables bobtail`

to let it work on XenServers?

.... wow!
