### ISSUE TITLE
A new created vdi has wrong size for physical-utilisation

### ISSUE THREAD

**Issue by djmoonshine** [rposudnevskiy/RBDSR#31]
If I create a new VDI the physical-utilisation size shown when running xe vdi-param-list uuid=<my vdi uuid> is incorrect.
I'm running XenServer7, ceph version 10.2.3 and the latest rbdsr code.

This is the values of a 10GB image.

virtual-size ( RO): 10737418240
physical-utilisation ( RO): 11258999068426240

This affects for instance if i try to run a move on it, then this value is checked when XenServer decides where there is space enough to place it.

This is not a very big issue since there is a work-around and that is to run xe sr-scan uuid=<my sr uuid>, after the values are correct.

virtual-size ( RO): 10737418240
physical-utilisation ( RO): 10737418240

**Comment by rposudnevskiy** [comment]
Fixed
