### ISSUE TITLE
the error when delete snapshot

### ISSUE THREAD

**Issue by suzj801** [rposudnevskiy/RBDSR#33]
cephutil.py
line 285:
`vdi_ref = self.session.xenapi.VDI.get_by_uuid(vdi_uuid)`
the right is:
`vdi_ref = self.session.xenapi.VDI.get_by_uuid(clone_uuid)`

**Comment by rposudnevskiy** [comment]
Yes, you are right. Could you please make pull request for it. 
Thank you.
