### ISSUE TITLE
install.sh problems

### ISSUE THREAD

**Issue by erdosip** [rposudnevskiy/RBDSR#38]
Hy!

I just used your script and found 2 bug in the install.sh...

The first one is the if statement, cause it's stopped the running.
I put 3 ";" after the closing "]" tags, and the script goes forward...

The second one is the sparse_dd saving/copying.
First you mv the original, with -orig ending, and it's fine.
After that, you run this "cp bins/sparse_dd /usr/libexec/xapi/sparse_dd-orig"

After the script finished, you loose the orig file, and the toolstack will not start, since the sparse_dd binary will missing.

Sorry, that I not push codes, but I'am not familiar with proper developing methods... :(

Regards,
 Peter

**Comment by rposudnevskiy** [comment]
Hi, 
Fixed.
Thank you very much.
