### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dlux95** [rposudnevskiy/RBDSR#41]
Hi

The project might not consist of much code but the code must be reliable and stable as much as possible. To get reliability we need some more documentation on the core of rdbsr. 
We should also have a list about things that need to be done.

Sincerely
Daniel

**Comment by rposudnevskiy** [comment]
Hi Daniel, 
You can find some documentation in HOWTOs directory. As for "to do" list it's really good idea. Do you have some proposals what to do next?

Best regards.
Roman

**Comment by dlux95** [comment]
Hi Roman,
The Documentation inside HOWTOs is more out of a users perspective. In order for other to help maintaining or fixing the code there must be a documentation about how RBDSR & XenServer handle specific things.
For Example: Think of a XenServer XM Request - We need to know which parts of the code gets executed at what time and how things are supposed to look.

 Proposed to do:
- writing code documentation
- build a testing table (ceph versions vs xenserver versions vs features) 
- is there somehow the option to build a plugin for xencenter to integrate rbd sr?

**Comment by rposudnevskiy** [comment]
Hi Daniel,
The RBDSR is just a plug-in (one of the many) for Xapi that handles some Xapi functions related to specific storage, Ceph in our case. The most of work are made by Xapi itself and RBDSR just helps Xapi to work properly with Ceph storage. For example, if Xapi need to make snapshot it calls snapshot method of RBDVDI class, which in its turn calls rbd command line tool to make Ceph snapshot. 
There are a lot of great documentation on Xapi. If you want to know how Xapi make specific things you can find it [here](http://xapi-project.github.io/xen-api/). For a example, [here](http://xapi-project.github.io/features/XSM/XSM.html) described how Xapi Live Migration works.  So I don't see the reason why we should include  such documentation here. May be just put more comments in code to describe some things that are not very clear. 
As for the testing of different combination of XenServer and Ceph versions, RBDSR doesn't use the functionality that is specific for different XenServer versions, I started to write it on XenServer 6.5 and it works on 7.1 without any meaningful changes in code. As for Ceph, RBDSR uses only one specific feature that allows to keep metadata with image and it is available starting from hummer release. 
Anyway it's a good idea to make tests for different combination of versions and any help with it will be useful. 
And finally XenCenter. XenCenter is closed source project. It supports some api for plug-ins but I'm afraid it doesn't help us with RBDSR integration

Best regards,
Roman
