### ISSUE TITLE
Questions about support/maintainability

### ISSUE THREAD

**Issue by ghost** [rposudnevskiy/RBDSR#46]
I'm currently evaluating options for using Ceph with XenServer and apart from iSCSI bridges it seems RBDSR is the best option right now, but I couldn't find any information on how "production ready" this is or if anyone uses RBDSR in production.

Is there any experience on how stable RBDSR is when applying XS patches/hotfixes? Also, would there be any possibility to get someone who'd (commercially) support this in case of problems with updates? I'd really like to use it for our company cluster but I won't get any permission to do so unless I can find someone who'd be able to fix problems with it.

**Comment by rposudnevskiy** [comment]
Hi,
Thank you for the interest to RBDSR project.  This plugin require installation of ceph-common, rbd-nbd and rbd-fuse packages and theirs dependencies into the Dom0. It is developing outside XenServer development process so any patches or updates can damage RBDSR. I'm not sure that it will become the part of XenServer or will be  officially supported by XenServer someday.
At the moment I don't have any plans for commercial support, may by later if it will make sens. 
Taking into account all the above I wouldn't recommend it for "production".
Anyway, I am ready to help with solving problems as far as possible, if you decide to use it. 

Thank you.
