### ISSUE TITLE
Problems with starting VMs on XenServer 7.2

### ISSUE THREAD

**Issue by mozg31337** [rposudnevskiy/RBDSR#53]
Hello guys. 

Followed the install guide. Went well without any issues. However, upon staring vm got an error:

tapdisk: experienced an error.

from what I can see, the disk on the ceph pool got created fine with the right size.

Any idea what is wrong or where to find more info?

thanks

**Comment by rposudnevskiy** [comment]
Hi,
Are there any errors in SMlog?
Could you please send SMlog and xensource.log from your sever.

**Comment by rposudnevskiy** [comment]
/var/log/SMlog
/var/log/xensource.log

**Comment by mozg31337** [comment]
Hi, the physical hard disk on my xenserver has died before I got the logs. I will be reinstalling it later on this week and if I have the same issue, I will attach the log files. Thanks

**Comment by mozg31337** [comment]
Hi. After the server rebuild I had the same error.  The log files attached.
FIY, running this command on the xenserver seems to work okay:

[root@arh-cloudhost14 ~]# rbd -p RBD_XenStorage-2fab8a69-2360-4ec4-82af-18f9fc756426 ls -l
NAME                                        SIZE PARENT FMT PROT LOCK
VHD-134f70e1-b19f-40af-ac9b-ef401a9844fd 102400M          2


[logs.zip](https://github.com/rposudnevskiy/RBDSR/files/1143288/logs.zip)

**Comment by mozg31337** [comment]
A quick glance at the logs shows this error:

Jul 12 21:50:05 arh-cloudhost14 SM: [19434] ['rbd-nbd', '--device', '/dev/nbd1', '--nbds_max', '64', 'map', 'RBD_XenStorage-2fab8a69-2360-4ec4-82af-18f9fc756426/VHD-134f70e1-b19f-40af-ac9b-ef401a9844fd', '--name', 'client.admin']
Jul 12 21:50:05 arh-cloudhost14 SM: [19434] FAILED in util.pread: (rc 1) stdout: '', stderr: 'rbd-nbd: unknown args: --name

Running this command: 

rbd-nbd --device /dev/nbd1 --nbds_max 64 --name client.admin map RBD_XenStorage-2fab8a69-2360-4ec4-82af-18f9fc756426/VHD-134f70e1-b19f-40af-ac9b-ef401a9844fd

indeed produces: 
rbd-nbd: unknown command: --name

[root@arh-cloudhost14 ~]# rpm -qa \* |grep rbd-nbd
rbd-nbd-10.2.8-0.el7.x86_64

Do you have any idea?

**Comment by rposudnevskiy** [comment]
Hi, 
This is the same problem as in #44.
It seems that in the latest Ceph updates they removed '--name' option of the rbd-nbd command.

**Comment by mozg31337** [comment]
indeed, they seems to have removed it a few things from their latest release. However, #44 relates to ceph branch 12.x whereas I am on 10.x. Also, looking at the fix in the bug report, it will not apply to ppl with ceph 10.x branch. 

Can we just remove the --name parameter from the options when running rbd-nbd command? Would this help to fix the issue?

**Comment by rposudnevskiy** [comment]
Hi,
The issue fixed with last commit.
The command "rbd-nbd map/unmap" replaced with "rbd nbd map/unmap" which supports '--conf' and '--name' arguments
