### ISSUE TITLE
install.sh script error cp -n

### ISSUE THREAD

**Issue by emanzx** [rposudnevskiy/RBDSR#57]
Hi.. I got this error when running the install script. and the the process crash
cp: invalid option -- n

Install the release.asc key
error: https://download.ceph.com/keys/release.asc: import read failed(-1).
Install new Repos
cp: invalid option -- n
Try `cp --help' for more information.

**Comment by rposudnevskiy** [comment]
Hi,
Which version of XenServer do you use?

**Comment by emanzx** [comment]
6.5.. or its already not supported?

**Comment by rposudnevskiy** [comment]
Could you please try to replace 'cp -n' with 'cp -f' in install.sh (it's in 9th line of the install.sh)?

**Comment by emanzx** [comment]
I think its not just issues with cp.. i try manually install and setup the repo.. but ultimately.. im stuck at this.. 

[root@xenserver-01 yum.repos.d]# yum install -y snappy leveldb gdisk python-argparse gperftools-libs fuse fuse-libs
base                                                                                                                                                                                 | 1.1 kB     00:00     
base/primary                                                                                                                                                                         | 1.3 MB     00:05     
base                                                                                                                                                                                              3662/3662
ceph                                                                                                                                                                                 | 2.9 kB     00:00     
ceph/primary_db                                                                                                                                                                      | 291 kB     00:01     
http://download.ceph.com/rpm-jewel/el7/x86_64/repodata/df234c3595641714fae981bd5e9b20189caf71c44ee49ecd1d526673c2c3c9c0-primary.sqlite.bz2: [Errno -3] Error performing checksum
Trying other mirror.
ceph/primary_db                                                                                                                                                                      | 291 kB     00:00     
http://download.ceph.com/rpm-jewel/el7/x86_64/repodata/df234c3595641714fae981bd5e9b20189caf71c44ee49ecd1d526673c2c3c9c0-primary.sqlite.bz2: [Errno -3] Error performing checksum
Trying other mirror.
Error: failure: repodata/df234c3595641714fae981bd5e9b20189caf71c44ee49ecd1d526673c2c3c9c0-primary.sqlite.bz2 from ceph: [Errno 256] No more mirrors to try.

I dont know what to do with this..

**Comment by rposudnevskiy** [comment]
Could you please execute 
cat /etc/centos-release on your XenServer

**Comment by rposudnevskiy** [comment]
Hi,
I think the reason why you received the "Error performing checksum" message is that you didn't install release.asc key that is used to verify ceph packages. 
You received an error on installing release.asc .
Do you have internet access on your XenServer?
