### ISSUE TITLE
Sometimes can't boot up VM with two or more VDI

### ISSUE THREAD

**Issue by wj761031** [rposudnevskiy/RBDSR#60]
Sorry for my poor English
I used Xenserver 7.1 and Ceph jewel (10.2.10)
It works with one VM with one VDI
When I attach another VDI to VM, it became unstable
sometimes it can reboot normally, sometimes it can't, and  I will get "tapdisk experienced an error" or "VDI is not available"

**Comment by rposudnevskiy** [comment]
Hi,
In this logfile `/var/log/SMlog` should be a detailed error message.  Could you please check it.

**Comment by wj761031** [comment]
Hi
I found those error log in /var/log/SMlog
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413] ***** ['/usr/sbin/tap-ctl', 'open', '-p', '15788', '-m', '0', '-a', 'vhd:/run/sr-mount/de8b4afd-2032-4b6b-b53b-39947dd107a8/11abdbed-9e49-4a4a-b02a-bd4e3b703d09', '-t', '40'] failed: status=2, pid=15800, errmsg=No such file or directory: EXCEPTION <class 'blktap2.CommandFailure'>, ['/usr/sbin/tap-ctl', 'open', '-p', '15788', '-m', '0', '-a', 'vhd:/run/sr-mount/de8b4afd-2032-4b6b-b53b-39947dd107a8/11abdbed-9e49-4a4a-b02a-bd4e3b703d09', '-t', '40'] failed: status=2, pid=15800, errmsg=No such file or directory
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]   File "/opt/xensource/sm/blktap2.py", line 794, in launch_on_tap
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]     TapCtl.open(pid, minor, _type, path, options)
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]   File "/opt/xensource/sm/blktap2.py", line 404, in open
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]     cls._pread(args)
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]   File "/opt/xensource/sm/blktap2.py", line 293, in _pread
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]     tapctl._wait(quiet)
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]   File "/opt/xensource/sm/blktap2.py", line 282, in _wait
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]     raise self.CommandFailure(self.cmd, **info)
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413] ['/usr/sbin/tap-ctl', 'free', '-m', '0']
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15750]   pread SUCCESS
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15750] ['ln', '-sf', '/dev/nbd/RBD_XenStorage-de8b4afd-2032-4b6b-b53b-39947dd107a8/VHD-be76ad1a-a043-4539-b4bd-28423e189c24', '/run/sr-mount/de8b4afd-2032-4b6b-b53b-39947dd107a8/be76ad1a-a043-4539-b4bd-28423e189c24']
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15750]   pread SUCCESS
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]  = 0
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413] Exception in activate/attach
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413] Removed host key host_OpaqueRef:540ae057-938c-f11f-95d6-cce89bb8ac3a for 11abdbed-9e49-4a4a-b02a-bd4e3b703d09
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413] ***** BLKTAP2:<function _activate_locked at 0x279cde8>: EXCEPTION <class 'blktap2.TapdiskFailed'>, Tapdisk(vhd:/run/sr-mount/de8b4afd-2032-4b6b-b53b-39947dd107a8/11abdbed-9e49-4a4a-b02a-bd4e3b703d09): ['/usr/sbin/tap-ctl', 'open', '-p', '15788', '-m', '0', '-a', 'vhd:/run/sr-mount/de8b4afd-2032-4b6b-b53b-39947dd107a8/11abdbed-9e49-4a4a-b02a-bd4e3b703d09', '-t', '40'] failed: status=2, pid=15800, errmsg=No such file or directory
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]   File "/opt/xensource/sm/blktap2.py", line 87, in wrapper
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]     ret = op(self, *args)
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]   File "/opt/xensource/sm/blktap2.py", line 1583, in _activate_locked
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]     dev_path = self._activate(sr_uuid, vdi_uuid, options)
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]   File "/opt/xensource/sm/blktap2.py", line 1627, in _activate
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]     self._get_pool_config(sr_uuid).get("mem-pool-size"))
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]   File "/opt/xensource/sm/blktap2.py", line 1302, in _tap_activate
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]     options)
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]   File "/opt/xensource/sm/blktap2.py", line 823, in launch_on_tap
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]     raise TapdiskFailed(cls.Arg(_type, path), ctl)
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413] lock: released /var/lock/sm/11abdbed-9e49-4a4a-b02a-bd4e3b703d09/vdi
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413] ***** tapdisk failed exception: Tapdisk(vhd:/run/sr-mount/de8b4afd-2032-4b6b-b53b-39947dd107a8/11abdbed-9e49-4a4a-b02a-bd4e3b703d09): ['/usr/sbin/tap-ctl', 'open', '-p', '15788', '-m', '0', '-a', 'vhd:/run/sr-mount/de8b4afd-2032-4b6b-b53b-39947dd107a8/11abdbed-9e49-4a4a-b02a-bd4e3b703d09', '-t', '40'] failed: status=2, pid=15800, errmsg=No such file or directory: EXCEPTION <class 'blktap2.TapdiskFailed'>, Tapdisk(vhd:/run/sr-mount/de8b4afd-2032-4b6b-b53b-39947dd107a8/11abdbed-9e49-4a4a-b02a-bd4e3b703d09): ['/usr/sbin/tap-ctl', 'open', '-p', '15788', '-m', '0', '-a', 'vhd:/run/sr-mount/de8b4afd-2032-4b6b-b53b-39947dd107a8/11abdbed-9e49-4a4a-b02a-bd4e3b703d09', '-t', '40'] failed: status=2, pid=15800, errmsg=No such file or directory
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]   File "/opt/xensource/sm/SRCommand.py", line 110, in run
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]     return self._run_locked(sr)
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]   File "/opt/xensource/sm/SRCommand.py", line 159, in _run_locked
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]     rv = self._run(sr, target)
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]   File "/opt/xensource/sm/SRCommand.py", line 264, in _run
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]     writable, caching_params)
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]   File "/opt/xensource/sm/blktap2.py", line 1536, in activate
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]     if self._activate_locked(sr_uuid, vdi_uuid, options):
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]   File "/opt/xensource/sm/blktap2.py", line 87, in wrapper
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]     ret = op(self, *args)
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]   File "/opt/xensource/sm/blktap2.py", line 1583, in _activate_locked
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]     dev_path = self._activate(sr_uuid, vdi_uuid, options)
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]   File "/opt/xensource/sm/blktap2.py", line 1627, in _activate
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]     self._get_pool_config(sr_uuid).get("mem-pool-size"))
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]   File "/opt/xensource/sm/blktap2.py", line 1302, in _tap_activate
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]     options)
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]   File "/opt/xensource/sm/blktap2.py", line 823, in launch_on_tap
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]     raise TapdiskFailed(cls.Arg(_type, path), ctl)
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15416] PhyLink(/dev/sm/phy/de8b4afd-2032-4b6b-b53b-39947dd107a8/be76ad1a-a043-4539-b4bd-28423e189c24) -> /run/sr-mount/de8b4afd-2032-4b6b-b53b-39947dd107a8/be76ad1a-a043-4539-b4bd-28423e189c24
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413] Raising exception [453, tapdisk experienced an error [opterr=No such file or directory]]
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413] ***** RBD: EXCEPTION <class 'SR.SROSError'>, tapdisk experienced an error [opterr=No such file or directory]
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]   File "/opt/xensource/sm/SRCommand.py", line 353, in run
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]     ret = cmd.run(sr)
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]   File "/opt/xensource/sm/SRCommand.py", line 125, in run
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]     os.strerror(e.get_error().get_error_code()))
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]   File "/opt/xensource/sm/xs_errors.py", line 52, in __init__
Nov 30 10:35:57 SB01SR-X-Z09 SM: [15413]     raise SR.SROSError(errorcode, errormessage)

**Comment by rposudnevskiy** [comment]
If it is possible could you send me to my email full  /var/log/SMlog.
Thank you.

**Comment by wj761031** [comment]
Hi
I sent the SMlog to ramzes_r@yahoo.com
please help to check.
thank you very much.

**Comment by rposudnevskiy** [comment]
Thank you.
One more question. Do you use v2?

**Comment by wj761031** [comment]
I have try v1 and v2 all have this problem
This SMlog is from v2
May I know need to give you v1's log?

**Comment by rposudnevskiy** [comment]
It is enough for now.
I am trying to diagnose the problem.
I will let you know.

**Comment by wj761031** [comment]
Ok, thank you!

**Comment by rposudnevskiy** [comment]
With last commits, the issues with multiple VDI should be fixed
