### ISSUE TITLE
Fix README instructions

### ISSUE THREAD

**Issue by learningdaily** [rposudnevskiy/RBDSR#66]
Recently working on adding RBDSR to a new XenServer install, ran script and saw a 404 error.

Resolved by changing the following; notice **master** to **v1.0**

` # sh <(curl -s https://raw.githubusercontent.com/rposudnevskiy/RBDSR/master/netinstall.sh) jewel`

to

` # sh <(curl -s https://raw.githubusercontent.com/rposudnevskiy/RBDSR/v1.0/netinstall.sh) jewel`

**Comment by rposudnevskiy** [comment]
Fixed.
Thank you.
