### ISSUE TITLE
Another Bug: 'RBDSR' object has no attribute 'CEPH_USER' on Scan SR

### ISSUE THREAD

**Issue by mhoffmann75** [rposudnevskiy/RBDSR#7]
Just another bug with commit 30:

> Aug  5 09:09:36 pns-xen06 SM: [12284] ****\* RBD: EXCEPTION <type 'exceptions.AttributeError'>, 'RBDSR' object has no attribute 'CEPH_USER'
> Aug  5 09:09:36 pns-xen06 SM: [12284]   File "/opt/xensource/sm/SRCommand.py", line 350, in run
> Aug  5 09:09:36 pns-xen06 SM: [12284]     sr = driver(cmd, cmd.sr_uuid)
> Aug  5 09:09:36 pns-xen06 SM: [12284]   File "/opt/xensource/sm/SR.py", line 147, in **init**
> Aug  5 09:09:36 pns-xen06 SM: [12284]     self.load(sr_uuid)
> Aug  5 09:09:36 pns-xen06 SM: [12284]   File "/opt/xensource/sm/RBDSR", line 178, in load
> Aug  5 09:09:36 pns-xen06 SM: [12284]     cephutils.SR.load(self,sr_uuid, ceph_user)
> Aug  5 09:09:36 pns-xen06 SM: [12284]   File "/opt/xensource/sm/cephutils.py", line 168, in load
> Aug  5 09:09:36 pns-xen06 SM: [12284]     self.RBDPOOLs = self._get_srlist()
> Aug  5 09:09:36 pns-xen06 SM: [12284]   File "/opt/xensource/sm/cephutils.py", line 155, in _get_srlist
> Aug  5 09:09:36 pns-xen06 SM: [12284]     cmdout = util.pread2(["ceph", "df", "--format", "json", "--name", self.CEPH_USER])
> Aug  5 09:09:36 pns-xen06 SM: [12284]

I wonder if this has been tested?

**Comment by Emmenemoi** [comment]
It has been tested after ansible deploy, but not against manual deploy.
And I'm facing snapshot problems and other so it is difficult to deep test.
I'll check this one.

**Comment by Emmenemoi** [comment]
Fixed
