### ISSUE TITLE
v3.0 issue

### ISSUE THREAD

**Issue by blodone** [rposudnevskiy/RBDSR#77]
Hi, 

I wanted to get the v3.0 branch into our repository so we could develop with you.
somehow the merge was not automatically able and i wanted to do it with command line and deleted the branch (i was sure it was with the pull request and our repository).

Github deleted your v3.0 and i mistakenly created it when searching it again.

Perhaps its better if you remove the ability for me to push or delete at your branches. We would create pull requests.

It's Friday 13th... sorry for the mistake

**Comment by rposudnevskiy** [comment]
it's ok. I have recovered the v3
