### ISSUE TITLE
v3.0 XCP-ng 7.5 got error message on pluggin pbd

### ISSUE THREAD

**Issue by northbear** [rposudnevskiy/RBDSR#83]
Hi, again... 
I've got error message on last stage of configuring ceph with XCP-ng 7.5:

```
[root@xcp-tst ~]# xe pbd-plug uuid=$( cat xcp-pbd.uuid )
There was an SR backend failure.
status: ObjectNotFound
stdout: [errno 2] error opening pool 'rbd+raw+qdisk://ceph/eeab8e6c-7480-45bf-a9e7-c16d9f96bfc9'
stderr: <unknown>
```
But actual pool name is:
```
[root@xcp-tst ~]# ssh root@${CEPH_MAN_SERVER} 'ceph osd pool ls '
RBD_XenStorage-eeab8e6c-7480-45bf-a9e7-c16d9f96bfc9
```
I suppose that name of pool in URL provided in error message should be the same as pool name in ceph. But I'm not sure...

**Comment by rposudnevskiy** [comment]
Hi, could please send me `/var/log/SMlog`  and `/var/log/xensource.log` from you XCP-ng 7.5 server.

**Comment by northbear** [comment]
Tnx for fixing... It works well now...
