### ISSUE TITLE
mkdir_p failed

### ISSUE THREAD

**Issue by ddimension** [rposudnevskiy/RBDSR#93]
Hi!

Without this patch:
`--- qemudisk.py	2018-10-10 17:33:52.284540367 +0200
+++ /usr/lib/python2.7/site-packages/xapi/storage/libs/librbd/qemudisk.py	2018-10-10 17:33:40.881224250 +0200
@@ -35,7 +35,7 @@ def create(dbg, uri):
     if vdi_type not in IMAGE_TYPES:
         raise Exception('Incorrect VDI type')
 
-    mkdir_p(QEMU_DP_SOCKET_DIR, 0o0700)
+    mkdir_p(QEMU_DP_SOCKET_DIR)
     nbd_sock = QEMU_DP_SOCKET_DIR + "/qemu-nbd.{}".format(vdi_uuid)
     qmp_sock = QEMU_DP_SOCKET_DIR + "/qmp_sock.{}".format(vdi_uuid)
     qmp_log  = QEMU_DP_SOCKET_DIR + "/qmp_log.{}".format(vdi_uuid)
`
I get errors about invalid 2nd arguement on mkdir_p. XCP-NG 7.5 installation was fresh.

**Comment by rposudnevskiy** [comment]
Hi,
Thank you
Issue fixed.
