### ISSUE TITLE
v3.0 cannot activate HA on xcp-cluster with ceph storage

### ISSUE THREAD

**Issue by northbear** [rposudnevskiy/RBDSR#94]
I cannot activate HA on xcp-ng 2 nodes cluster with ceph mimic by RBDSR v3.0. After trying It provides error notification: "This operation cannot be performed because VDI OpaqueRef: e95c4457-a241... could not be properly attached to the VM"
Logs attached below: 
[SMlog.ha-start-fails.log](https://github.com/rposudnevskiy/RBDSR/files/2483146/SMlog.ha-start-fails.log)
[xensource.ha-start-fails.log](https://github.com/rposudnevskiy/RBDSR/files/2483147/xensource.ha-start-fails.log)

**Comment by northbear** [comment]
It looks like it's an issue of xapi. It tries to call SR.attach with incorrect set of configuration keys.

**Comment by rposudnevskiy** [comment]
Hi,
It should work after commit [d7f9a35](https://github.com/rposudnevskiy/RBDSR/commit/d7f9a35768ff9eb72b5bcd5f08813549c48b09a8)
Just create new SR as described in README or if you want to use previously created SR use this method:
- forget the SR
```
xe pbd-unplug uuid={uuid of PBD for your SR}
xe pbd-destroy uuid={uuid of PBD for your SR}
xe sr-forget uuid={uuid of your SR}
```
- reintroduce the SR
```
xe sr-introduce name-label="CEPH RBD Storage" type=rbdsr uuid={uuid of your SR} shared=true content-type=user
xe pbd-create sr-uuid=4ceb0f8a-1539-40a4-bee2-450a025b04e1 host-uuid={host uuid} device-config:sr_uuid={uuid of your SR} device-config:cluster=ceph device-config:image-format=raw device-config:datapath=qdisk
xe pbd-plug uuid={pbd uuid}
```
It is important to add `device-config:sr_uuid` parameter on PBD creating

I am not sure that this is a bug of XAPI as you mentioned here [xcp-ng/xcp#81](https://github.com/xcp-ng/xcp/issues/81). Maybe this is intended behavior of XAPI. So the plugin add sr_uuid to config on SR creating, but you should specify `device-config:sr_uuid` if you introduce the existing SR

**Comment by northbear** [comment]
Good job. Thanks... 
I supposed that the variable sr_uuid should be initialized in any case on that stage. At least I didn't find any reason why it cannot be initialized. The SR already exists anyway. Though they didn't use it at that time it may be used later in the next versions. 
Sorry, I'm not tracking the report. I've moved to another company and position and now I'm far away from Ceph and XCP.
Anyway, I have to say that except of couple small bugs the plugin worked pretty well. Way to go!
