### ISSUE TITLE
Can't Add Vol in CEPH RBD Storage

### ISSUE THREAD

**Issue by kenneth104** [rposudnevskiy/RBDSR#98]
I chage a lot of fix in https://github.com/rposudnevskiy/RBDSR/issues/97
So,i can link the Ceph RBD in xen-ng 7.6
And Rescan it's WORK

But,i want add vol or any import the CEPH RBD Storage are ERROR

`SCRIPT_FAILED - /usr/libexec/xapi-storage-script/volume/org.xen.xapi.storage.rbdsr/Volume.create - non-zero exit and bad json on stdout - 1`

Found the /var/log/SMlog

`Jan  7 17:19:51 xcp-ng-hpayspbf SMAPIv3: [10175] - ERROR - Unhandled exception#012Traceback (most recent call last):#012  File "/usr/libexec/xapi-storage-script/volume/org.xen.xapi.storage.rbdsr/Volume.create", line 15, in <module>#012    from xapi.storage.libs.librbd.volume import RAWVolume, QCOW2Volume#012  File "/usr/lib/python2.7/site-packages/xapi/storage/libs/librbd/volume.py", line 17, in <module>#012    from xapi.storage.libs.util import get_current_host_uuid, call#012ImportError: No module named util`

In` /usr/lib/python2.7/site-packages/xapi/storage/libs`   does not have any util* 

But I found history have xapi/storage/libs/utils.py not have import `call` in volume.py line 17 and some *.py need `call`

**Comment by rposudnevskiy** [comment]
Hi,
The problem is that RBDSR plugin uses module `util` from `xapi-storage-plugins` package from XenServer which was made closed-source by Citrix. For this reason, this package was removed from XCP-ng
Also, this package provides `qemuback` service which is required for all plugins which use qemu qdisk datapath

**Comment by kenneth104** [comment]
OK; get it~
